name 'redhat-access-insights-client'
maintainer 'Dan Varga'
maintainer_email 'dvarga@redhat.com'
license 'MIT'
description 'Installs/Configures redhat-access-insights-client'
long_description 'Installs/Configures redhat-access-insights-client'
version '0.1.0'
